version: '3.3'

services:

    moviepilot:
        stdin_open: true
        tty: true
        container_name: moviepilot-v2
        hostname: moviepilot-v2

        network_mode: host
        # networks:
        #   - moviepilot
        # ports:
        #    - target: 3000
        #      published: 3000
        #      protocol: tcp
        volumes:
            - '/volume1/MG07:/volume1/MG07'
            - '/volume2/docker/moviepilot-v2/config:/config'
            - '/volume2/docker/moviepilot-v2/core:/moviepilot/.cache/ms-playwright'
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
        environment:
            - 'NGINX_PORT=3000'
            - 'PORT=3001'
            - 'PUID=0'
            - 'PGID=0'
            - 'UMASK=000'
            - 'TZ=Asia/Shanghai'
            - 'AUTH_SITE=iyuu'
            # - 'IYUU_SIGN=xxx'
            # - 'SUPERUSER=admin'
            # - 'API_TOKEN=无需手动配置，系统会自动生成。如果需要自定义配置，必须为16位以上的复杂字符串'
        restart: always
        image: jxxghp/moviepilot-v2:latest

networks:
  moviepilot:
    name: moviepilot