services:
  emby:
    image: emby/embyserver:latest
    container_name: emby
    restart: unless-stopped
    network_mode: bridge  # 或使用 host 模式（见下方说明）
    ports:
      - "8096:8096"       # Web 界面端口
      - "8920:8920"       # HTTPS 端口（可选）     
    environment:
      - TZ=Asia/Shanghai  # 时区设置（按需修改）
      - UID=100          # 宿主机的用户ID（ssh连接主机查看）
      - GID=100          # 宿主机的组ID（ssh连接主机查看）
    volumes:
      - ./config:/config          # 配置文件存储位置

