services:
    iyuuplus-dev:
        stdin_open: true
        tty: true
        volumes:
            - ./iyuu:/iyuu
            - ./data:/data
        ports:
            - "8780:8780"
        container_name: IYUUPlus
        restart: always
        image: iyuucn/iyuuplus-dev:latest
