version: '3'
services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest  # 可替换为特定版本如 `4.6.7`
    container_name: qbittorrent
    environment:
      - WEBUI_PORT=8080  # Web界面访问端口
    volumes:
      - ./config:/config  # 配置文件存储路径
    ports:
      - 8080:8080  # Web UI端口映射
      - 6881:6881    # BT协议监听端口（TCP）
      - 6881:6881/udp  # BT协议监听端口（UDP）
    restart: unless-stopped
